name: Octopus Deploy - Microsite Pull Request Deployment

on:
  workflow_call:
    inputs:
      octopus_project_name:
        required: true
        type: string
      package_id:
        required: true
        type: string
      node_version:
        required: false
        type: string
        default: '18'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  branch_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    env:
      SHOULD_DEPLOY: ${{ secrets.OCTOPUS_SERVER_URL != '' || '' }}
      OCTOPUS_SPACE: "Microsites"
      OCTOPUS_PROJECT_NAME: ${{ inputs.octopus_project_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: PNPM and Playwright install
        run: |
          echo; echo "cd to workspace"
          cd $GITHUB_WORKSPACE
          echo; echo "listing"
          ls
          echo; echo "NPM install"
          pnpm install

      - name: Astro build and test
        run: |
          export NODE_OPTIONS=--max_old_space_size=4096
          pnpm dev:img
          pnpm test
          pnpm crawl

      - name: Set Version
        run: |
          echo "PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Check output
        run: |
          echo; echo "cd to workspace"
          cd $GITHUB_WORKSPACE
          echo; echo "listing"
          ls

      - name: Create a Zip package 🐙
        id: package
        uses: OctopusDeploy/create-zip-package-action@v3
        with:
          package_id: ${{ inputs.package_id }}
          version: "${{ env.PACKAGE_VERSION }}-pullrequest"
          base_path: "./dist"
          output_folder: "./artifacts"
          files: |
            **/*.*

      - name: Login to Octopus Deploy 🐙
        uses: OctopusDeploy/login@v1.0.3
        if: ${{ env.SHOULD_DEPLOY }}
        with:
          server: ${{ secrets.OCTOPUS_SERVER_URL }}
          service_account_id: ${{ secrets.OCTOPUS_SERVICE_ACCOUNT_ID }}

      - name: Push a package to Octopus Deploy 🐙
        uses: OctopusDeploy/push-package-action@v4.0.0
        if: ${{ env.SHOULD_DEPLOY }}
        with:
          packages: ${{ steps.package.outputs.package_file_path }}

      - name: Let people download package
        uses: actions/upload-artifact@v4
        if: ${{ ! env.SHOULD_DEPLOY }}
        with:
          name: ${{ inputs.package_id }}
          path: ${{ steps.package.outputs.package_file_path }}

      - name: Push build information to Octopus Deploy 🐙
        uses: OctopusDeploy/push-build-information-action@v4.1.0
        if: ${{ env.SHOULD_DEPLOY }}
        with:
          version: "${{ env.PACKAGE_VERSION }}-pullrequest"
          packages: ${{ steps.package.outputs.package_file_path }}

      - name: Create Ephemeral Environment
        id: create_ephemeral_environment
        uses: OctopusDeploy/create-ephemeral-environment@v1.1.1
        with:
          name: pr${{ github.event.pull_request.number }}
          project: ${{ env.OCTOPUS_PROJECT_NAME }}

      - name: Create a release in Octopus Deploy 🐙
        id: create_release
        uses: OctopusDeploy/create-release-action@v4.1.1
        if: ${{ env.SHOULD_DEPLOY }}
        with:
          project: ${{ env.OCTOPUS_PROJECT_NAME }}
          channel: "Ephemeral Environments"
          git_ref: ${{ github.head_ref || github.ref_name }}
          git_commit: ${{ github.event.after || github.event.pull_request.head.sha }}
          package_version: "${{ env.PACKAGE_VERSION }}-pullrequest"
          custom_fields: |
            PullRequestNumber: ${{ github.event.pull_request.number }}

      - name: Deploy release to ephemeral environment 🐙
        id: deploy_release
        if: ${{ env.SHOULD_DEPLOY }}
        uses: OctopusDeploy/deploy-release-action@v4
        with:
          project: ${{ env.OCTOPUS_PROJECT_NAME }}
          release_number: ${{ steps.create_release.outputs.release_number }}
          environments: 'pr${{ github.event.pull_request.number }}'

      - name: Await deployment completion 🐙
        if: ${{ env.SHOULD_DEPLOY }}
        uses: OctopusDeploy/await-task-action@v4
        with:
          server_task_id: ${{ fromJson(steps.deploy_release.outputs.server_tasks)[0].serverTaskId }}
          polling_interval: 10
          timeout_after: 900
